### ISSUE TITLE
sarp_inventory/sourceS.lua problem.

### ISSUE THREAD

**Issue by ChuckyNorrison** [HexonDev/mta-sarp#1]
Hello, i found error in sarp_invertory/sourceS.lua.
debugscript 3 :
sarp_inventory/sourceS.lua:1396: dbPoll failed; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELECT *FROM items ORDER BY dbID DESC LIMIT 1'at line 1

ERROR:sarp_inventory/sourceS.lua:1396:attempt to index a boolean value

code :
 				dbQuery(
					function (qh, sourceElement)
						if isElement(sourceElement) then
							local result = dbPoll(qh, 0, true)[2][1][1]

							if result then
								addItemEx(sourceElement, result.dbID, result.slot, result.itemId, result.amount, result.data1, result.data2, result.data3)

								triggerItemEvent(sourceElement, "addItem", getElementType(sourceElement), result)
							end
						end
					end, {sourceElement}, connection, "INSERT INTO items (itemId, slot, amount, data1, data2, data3, ownerType, ownerId) VALUES (?,?,?,?,?,?,?,?); SELECT * FROM items ORDER BY dbID DESC LIMIT 1", itemId, slotId, amount, data1, data2, data3, ownerType, ownerId
				)

Error at line : 
`							local result = dbPoll(qh, 0, true)[2][1][1]`

Thanks for help!z

**Comment by ChuckyNorrison** [comment]
@HexonDev can u help please?

**Comment by HexonDev** [comment]
Hello!

Sorry, but this repostory archived, we can't help you
